erc: add AppImage unpacking

diff --git a/bin/erc b/bin/erc
--- a/bin/erc
+++ b/bin/erc
@@ -76,12 +76,26 @@ extract_archive()
 	local arc="$1"
 	shift
 
+	local type="$(get_archive_type "$arc")"
+	[ -n "$type" ] || fatal "Can't recognize type of $arc."
+
+	# TODO: move to patool
+	if [ "$type" = "exe" ] ; then
+		docmd $HAVE_7Z x "$arc"
+		exit
+	fi
+
+	if [ "$type" = "AppImage" ] || [ "$type" = "appimage" ] ; then
+		docmd chmod u+x "$arc" || fatal "Can't set executable permission"
+		docmd "$(realpath $arc)" --appimage-extract
+		mv squashfs-root "$(basename "$(basename "$arc" .AppImage)" .appimage)"
+		exit
+	fi
+
 	if have_patool ; then
         docmd patool $verbose extract "$arc" "$@"
 		return
 	fi
-
-	local type="$(get_archive_type "$arc")"
 
 	arc="$(realpath -s "$arc")"
 	tdir=$(mktemp -d $(pwd)/UXXXXXXXX) && cd "$tdir" || fatal
@@ -325,11 +339,6 @@ case $cmd in
         create_archive "$target" "$@"
         ;;
     e|x|-e|-x|u|-u|extract|unpack)          # HELPCMD: extract files from archive
-        # TODO: move to patool
-        if [ "$(get_archive_type "$1" 2>/dev/null)" = "exe" ] ; then
-            docmd $HAVE_7Z x "$1"
-            exit
-        fi
         extract_archive "$@"
         ;;
 # TODO: implement deletion
